services:
  fastrallyobedience.server:
    build:
      context: ./FastRallyObedience.Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # HTTP
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "myStrong_Password123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  fastrallyobedience.client:
    build:
      context: ./FastRallyObedience.Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  